version: 2
jobs:
  test:
    docker:
      - image: python:3.5
    working_directory: ~/python-client
    steps:
      - checkout

      - run:
          command: pip install --upgrade pip tox
      
      - run:
          command: | 
            tox -e lint
            tox -e py35
  
  pypi_upload:
    docker:
        - image: python:3.5
    steps:
      - checkout

      - run:
          command: |
            pip install --upgrade pip tox
            tox -e build_pypi

workflows:
  version: 2
  test:
    jobs:
      - test
  pypi_upload:
    jobs:
      - pypi_upload:
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/